package com.lhy.netty.protobuf;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BookResponseMsg.proto

public final class BookResponseMsgBuffer {
  private BookResponseMsgBuffer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BookResponseMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BookResponseMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bool success = 1;</code>
     *
     * <pre>
     *�Ƿ�����ɹ�
     * </pre>
     */
    boolean hasSuccess();
    /**
     * <code>required bool success = 1;</code>
     *
     * <pre>
     *�Ƿ�����ɹ�
     * </pre>
     */
    boolean getSuccess();

    /**
     * <code>required int64 userId = 2;</code>
     *
     * <pre>
     *�����û�
     * </pre>
     */
    boolean hasUserId();
    /**
     * <code>required int64 userId = 2;</code>
     *
     * <pre>
     *�����û�
     * </pre>
     */
    long getUserId();

    /**
     * <code>required string msg = 3;</code>
     *
     * <pre>
     *������Ϣ
     * </pre>
     */
    boolean hasMsg();
    /**
     * <code>required string msg = 3;</code>
     *
     * <pre>
     *������Ϣ
     * </pre>
     */
    java.lang.String getMsg();
    /**
     * <code>required string msg = 3;</code>
     *
     * <pre>
     *������Ϣ
     * </pre>
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    /**
     * <code>required int32 code = 4;</code>
     *
     * <pre>
     *����ָ��
     * </pre>
     */
    boolean hasCode();
    /**
     * <code>required int32 code = 4;</code>
     *
     * <pre>
     *����ָ��
     * </pre>
     */
    int getCode();

    /**
     * <code>required int64 trainId = 5;</code>
     *
     * <pre>
     *�𳵳���
     * </pre>
     */
    boolean hasTrainId();
    /**
     * <code>required int64 trainId = 5;</code>
     *
     * <pre>
     *�𳵳���
     * </pre>
     */
    long getTrainId();

    /**
     * <code>required int64 startTime = 6;</code>
     *
     * <pre>
     *����ʱ��
     * </pre>
     */
    boolean hasStartTime();
    /**
     * <code>required int64 startTime = 6;</code>
     *
     * <pre>
     *����ʱ��
     * </pre>
     */
    long getStartTime();

    /**
     * <code>required int64 ticketId = 7;</code>
     *
     * <pre>
     *��Ʊ�ɹ�������ƱƱ��
     * </pre>
     */
    boolean hasTicketId();
    /**
     * <code>required int64 ticketId = 7;</code>
     *
     * <pre>
     *��Ʊ�ɹ�������ƱƱ��
     * </pre>
     */
    long getTicketId();
  }
  /**
   * Protobuf type {@code BookResponseMsg}
   */
  public  static final class BookResponseMsg extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:BookResponseMsg)
      BookResponseMsgOrBuilder {
    // Use BookResponseMsg.newBuilder() to construct.
    private BookResponseMsg(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private BookResponseMsg() {
      success_ = false;
      userId_ = 0L;
      msg_ = "";
      code_ = 0;
      trainId_ = 0L;
      startTime_ = 0L;
      ticketId_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BookResponseMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              success_ = input.readBool();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              userId_ = input.readInt64();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              msg_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              code_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              trainId_ = input.readInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              startTime_ = input.readInt64();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              ticketId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BookResponseMsgBuffer.internal_static_BookResponseMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BookResponseMsgBuffer.internal_static_BookResponseMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BookResponseMsgBuffer.BookResponseMsg.class, BookResponseMsgBuffer.BookResponseMsg.Builder.class);
    }

    private int bitField0_;
    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_;
    /**
     * <code>required bool success = 1;</code>
     *
     * <pre>
     *�Ƿ�����ɹ�
     * </pre>
     */
    public boolean hasSuccess() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bool success = 1;</code>
     *
     * <pre>
     *�Ƿ�����ɹ�
     * </pre>
     */
    public boolean getSuccess() {
      return success_;
    }

    public static final int USERID_FIELD_NUMBER = 2;
    private long userId_;
    /**
     * <code>required int64 userId = 2;</code>
     *
     * <pre>
     *�����û�
     * </pre>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 userId = 2;</code>
     *
     * <pre>
     *�����û�
     * </pre>
     */
    public long getUserId() {
      return userId_;
    }

    public static final int MSG_FIELD_NUMBER = 3;
    private volatile java.lang.Object msg_;
    /**
     * <code>required string msg = 3;</code>
     *
     * <pre>
     *������Ϣ
     * </pre>
     */
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string msg = 3;</code>
     *
     * <pre>
     *������Ϣ
     * </pre>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string msg = 3;</code>
     *
     * <pre>
     *������Ϣ
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CODE_FIELD_NUMBER = 4;
    private int code_;
    /**
     * <code>required int32 code = 4;</code>
     *
     * <pre>
     *����ָ��
     * </pre>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 code = 4;</code>
     *
     * <pre>
     *����ָ��
     * </pre>
     */
    public int getCode() {
      return code_;
    }

    public static final int TRAINID_FIELD_NUMBER = 5;
    private long trainId_;
    /**
     * <code>required int64 trainId = 5;</code>
     *
     * <pre>
     *�𳵳���
     * </pre>
     */
    public boolean hasTrainId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int64 trainId = 5;</code>
     *
     * <pre>
     *�𳵳���
     * </pre>
     */
    public long getTrainId() {
      return trainId_;
    }

    public static final int STARTTIME_FIELD_NUMBER = 6;
    private long startTime_;
    /**
     * <code>required int64 startTime = 6;</code>
     *
     * <pre>
     *����ʱ��
     * </pre>
     */
    public boolean hasStartTime() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int64 startTime = 6;</code>
     *
     * <pre>
     *����ʱ��
     * </pre>
     */
    public long getStartTime() {
      return startTime_;
    }

    public static final int TICKETID_FIELD_NUMBER = 7;
    private long ticketId_;
    /**
     * <code>required int64 ticketId = 7;</code>
     *
     * <pre>
     *��Ʊ�ɹ�������ƱƱ��
     * </pre>
     */
    public boolean hasTicketId() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required int64 ticketId = 7;</code>
     *
     * <pre>
     *��Ʊ�ɹ�������ƱƱ��
     * </pre>
     */
    public long getTicketId() {
      return ticketId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSuccess()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTrainId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStartTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTicketId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, success_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, userId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getMsgBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, code_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, trainId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(6, startTime_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt64(7, ticketId_);
      }
      unknownFields.writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, success_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, userId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getMsgBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, code_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, trainId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, startTime_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, ticketId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static BookResponseMsgBuffer.BookResponseMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BookResponseMsgBuffer.BookResponseMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BookResponseMsgBuffer.BookResponseMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BookResponseMsgBuffer.BookResponseMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BookResponseMsgBuffer.BookResponseMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static BookResponseMsgBuffer.BookResponseMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static BookResponseMsgBuffer.BookResponseMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static BookResponseMsgBuffer.BookResponseMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static BookResponseMsgBuffer.BookResponseMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static BookResponseMsgBuffer.BookResponseMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(BookResponseMsgBuffer.BookResponseMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BookResponseMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BookResponseMsg)
        BookResponseMsgBuffer.BookResponseMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BookResponseMsgBuffer.internal_static_BookResponseMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BookResponseMsgBuffer.internal_static_BookResponseMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                BookResponseMsgBuffer.BookResponseMsg.class, BookResponseMsgBuffer.BookResponseMsg.Builder.class);
      }

      // Construct using BookResponseMsgBuffer.BookResponseMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        success_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        msg_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        code_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        trainId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        startTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        ticketId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BookResponseMsgBuffer.internal_static_BookResponseMsg_descriptor;
      }

      public BookResponseMsgBuffer.BookResponseMsg getDefaultInstanceForType() {
        return BookResponseMsgBuffer.BookResponseMsg.getDefaultInstance();
      }

      public BookResponseMsgBuffer.BookResponseMsg build() {
        BookResponseMsgBuffer.BookResponseMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public BookResponseMsgBuffer.BookResponseMsg buildPartial() {
        BookResponseMsgBuffer.BookResponseMsg result = new BookResponseMsgBuffer.BookResponseMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.success_ = success_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.msg_ = msg_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.code_ = code_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.trainId_ = trainId_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.startTime_ = startTime_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.ticketId_ = ticketId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BookResponseMsgBuffer.BookResponseMsg) {
          return mergeFrom((BookResponseMsgBuffer.BookResponseMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(BookResponseMsgBuffer.BookResponseMsg other) {
        if (other == BookResponseMsgBuffer.BookResponseMsg.getDefaultInstance()) return this;
        if (other.hasSuccess()) {
          setSuccess(other.getSuccess());
        }
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasMsg()) {
          bitField0_ |= 0x00000004;
          msg_ = other.msg_;
          onChanged();
        }
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (other.hasTrainId()) {
          setTrainId(other.getTrainId());
        }
        if (other.hasStartTime()) {
          setStartTime(other.getStartTime());
        }
        if (other.hasTicketId()) {
          setTicketId(other.getTicketId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSuccess()) {
          return false;
        }
        if (!hasUserId()) {
          return false;
        }
        if (!hasMsg()) {
          return false;
        }
        if (!hasCode()) {
          return false;
        }
        if (!hasTrainId()) {
          return false;
        }
        if (!hasStartTime()) {
          return false;
        }
        if (!hasTicketId()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        BookResponseMsgBuffer.BookResponseMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (BookResponseMsgBuffer.BookResponseMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean success_ ;
      /**
       * <code>required bool success = 1;</code>
       *
       * <pre>
       *�Ƿ�����ɹ�
       * </pre>
       */
      public boolean hasSuccess() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bool success = 1;</code>
       *
       * <pre>
       *�Ƿ�����ɹ�
       * </pre>
       */
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>required bool success = 1;</code>
       *
       * <pre>
       *�Ƿ�����ɹ�
       * </pre>
       */
      public Builder setSuccess(boolean value) {
        bitField0_ |= 0x00000001;
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool success = 1;</code>
       *
       * <pre>
       *�Ƿ�����ɹ�
       * </pre>
       */
      public Builder clearSuccess() {
        bitField0_ = (bitField0_ & ~0x00000001);
        success_ = false;
        onChanged();
        return this;
      }

      private long userId_ ;
      /**
       * <code>required int64 userId = 2;</code>
       *
       * <pre>
       *�����û�
       * </pre>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 userId = 2;</code>
       *
       * <pre>
       *�����û�
       * </pre>
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>required int64 userId = 2;</code>
       *
       * <pre>
       *�����û�
       * </pre>
       */
      public Builder setUserId(long value) {
        bitField0_ |= 0x00000002;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 userId = 2;</code>
       *
       * <pre>
       *�����û�
       * </pre>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object msg_ = "";
      /**
       * <code>required string msg = 3;</code>
       *
       * <pre>
       *������Ϣ
       * </pre>
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string msg = 3;</code>
       *
       * <pre>
       *������Ϣ
       * </pre>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string msg = 3;</code>
       *
       * <pre>
       *������Ϣ
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string msg = 3;</code>
       *
       * <pre>
       *������Ϣ
       * </pre>
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string msg = 3;</code>
       *
       * <pre>
       *������Ϣ
       * </pre>
       */
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000004);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>required string msg = 3;</code>
       *
       * <pre>
       *������Ϣ
       * </pre>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        msg_ = value;
        onChanged();
        return this;
      }

      private int code_ ;
      /**
       * <code>required int32 code = 4;</code>
       *
       * <pre>
       *����ָ��
       * </pre>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 code = 4;</code>
       *
       * <pre>
       *����ָ��
       * </pre>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <code>required int32 code = 4;</code>
       *
       * <pre>
       *����ָ��
       * </pre>
       */
      public Builder setCode(int value) {
        bitField0_ |= 0x00000008;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 code = 4;</code>
       *
       * <pre>
       *����ָ��
       * </pre>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000008);
        code_ = 0;
        onChanged();
        return this;
      }

      private long trainId_ ;
      /**
       * <code>required int64 trainId = 5;</code>
       *
       * <pre>
       *�𳵳���
       * </pre>
       */
      public boolean hasTrainId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int64 trainId = 5;</code>
       *
       * <pre>
       *�𳵳���
       * </pre>
       */
      public long getTrainId() {
        return trainId_;
      }
      /**
       * <code>required int64 trainId = 5;</code>
       *
       * <pre>
       *�𳵳���
       * </pre>
       */
      public Builder setTrainId(long value) {
        bitField0_ |= 0x00000010;
        trainId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 trainId = 5;</code>
       *
       * <pre>
       *�𳵳���
       * </pre>
       */
      public Builder clearTrainId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        trainId_ = 0L;
        onChanged();
        return this;
      }

      private long startTime_ ;
      /**
       * <code>required int64 startTime = 6;</code>
       *
       * <pre>
       *����ʱ��
       * </pre>
       */
      public boolean hasStartTime() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int64 startTime = 6;</code>
       *
       * <pre>
       *����ʱ��
       * </pre>
       */
      public long getStartTime() {
        return startTime_;
      }
      /**
       * <code>required int64 startTime = 6;</code>
       *
       * <pre>
       *����ʱ��
       * </pre>
       */
      public Builder setStartTime(long value) {
        bitField0_ |= 0x00000020;
        startTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 startTime = 6;</code>
       *
       * <pre>
       *����ʱ��
       * </pre>
       */
      public Builder clearStartTime() {
        bitField0_ = (bitField0_ & ~0x00000020);
        startTime_ = 0L;
        onChanged();
        return this;
      }

      private long ticketId_ ;
      /**
       * <code>required int64 ticketId = 7;</code>
       *
       * <pre>
       *��Ʊ�ɹ�������ƱƱ��
       * </pre>
       */
      public boolean hasTicketId() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required int64 ticketId = 7;</code>
       *
       * <pre>
       *��Ʊ�ɹ�������ƱƱ��
       * </pre>
       */
      public long getTicketId() {
        return ticketId_;
      }
      /**
       * <code>required int64 ticketId = 7;</code>
       *
       * <pre>
       *��Ʊ�ɹ�������ƱƱ��
       * </pre>
       */
      public Builder setTicketId(long value) {
        bitField0_ |= 0x00000040;
        ticketId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 ticketId = 7;</code>
       *
       * <pre>
       *��Ʊ�ɹ�������ƱƱ��
       * </pre>
       */
      public Builder clearTicketId() {
        bitField0_ = (bitField0_ & ~0x00000040);
        ticketId_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BookResponseMsg)
    }

    // @@protoc_insertion_point(class_scope:BookResponseMsg)
    private static final BookResponseMsgBuffer.BookResponseMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new BookResponseMsgBuffer.BookResponseMsg();
    }

    public static BookResponseMsgBuffer.BookResponseMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<BookResponseMsg> PARSER =
        new com.google.protobuf.AbstractParser<BookResponseMsg>() {
      public BookResponseMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new BookResponseMsg(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BookResponseMsg> getParserForType() {
      return PARSER;
    }

    public BookResponseMsgBuffer.BookResponseMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BookResponseMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BookResponseMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025BookResponseMsg.proto\"\203\001\n\017BookResponse" +
      "Msg\022\017\n\007success\030\001 \002(\010\022\016\n\006userId\030\002 \002(\003\022\013\n\003" +
      "msg\030\003 \002(\t\022\014\n\004code\030\004 \002(\005\022\017\n\007trainId\030\005 \002(\003" +
      "\022\021\n\tstartTime\030\006 \002(\003\022\020\n\010ticketId\030\007 \002(\003B\027B" +
      "\025BookResponseMsgBuffer"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_BookResponseMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BookResponseMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_BookResponseMsg_descriptor,
        new java.lang.String[] { "Success", "UserId", "Msg", "Code", "TrainId", "StartTime", "TicketId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
